name: movie_buddy
description: A movie app that helps to select movies easily.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  coverde: ^0.1.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_nested_navigation:
    git:
      url: https://github.com/g-30/flutter_nested_navigation.git
  gap: ^2.0.1
  hydrated_bloc: ^9.0.0
  ionicons: ^0.2.2
  melos: ^2.9.0
  movie_buddy_ui:
    path: packages/movie_buddy_ui
  movie_repository:
    path: packages/movie_repository
  optimized_cached_image: ^3.0.1
  path_provider: ^2.0.12
  sliding_up_panel: ^2.0.0+1
  stream_transform: ^2.1.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
