name: movie_buddy
description: A movie app that helps to select movies easily.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true
  generate: true
