name: platform_helper
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
