name: movie_buddy

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "**/*.g.dart"
  
