name: movie_buddy

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
jobs:
  build:
    uses: Orkunnnn/very_good_workflows/.github/workflows/main.yml@main
    with:
      coverage_excludes: "**/*.g.dart"
  
